// @vitest-environment node
import {beforeEach, describe, expect, it, vi} from 'vitest'
vi.mock('server-only',()=>({}))
vi.mock('@/lib/shopify/admin-access-token',()=>({getAdminAccessToken:vi.fn().mockResolvedValue('test-token')}))
vi.mock('@/lib/shopify/customer-account-oauth',()=>({getValidAccessToken:vi.fn(),queryCustomerAccountApi:vi.fn()}))
import {getValidAccessToken,queryCustomerAccountApi} from '@/lib/shopify/customer-account-oauth'
import {identity,checkOrigin,verifyPurchase,updateReviews,readInput} from '@/lib/reviews/server'
import {appendReview,moderateReview,visibleReviews,submitSchema,type Review,type ReviewDocument} from '@/lib/reviews/model'
const review:Review={id:'7510e770-33ef-44a7-991f-bf73cdbb2769',buyerId:'gid://shopify/Customer/1',author:'Buyer',body:'Not what I expected',rating:1,createdAt:'2026-09-26T00:00:00Z',status:'published',history:[]}
const empty:ReviewDocument={version:1,reviews:[]}
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('PRODUCT_REVIEWS_ENABLED','true');vi.stubEnv('REVIEW_OWNER_CUSTOMER_ID','gid://shopify/Customer/1');vi.stubEnv('SHOPIFY_CUSTOMER_ACCOUNT_SITE_URL','https://www.atpgroupservices.ae');vi.stubEnv('SHOPIFY_STORE_DOMAIN','test.myshopify.com')})
describe('review moderation and privacy',()=>{
 it('preserves negative ratings and removes private fields from public output',()=>{const r=visibleReviews(appendReview(empty,review))[0];expect(r.rating).toBe(1);expect(r).not.toHaveProperty('buyerId');expect(r).not.toHaveProperty('history')})
 it('hides, restores, records reason, blocks reposting a hidden review',()=>{const hidden=moderateReview(appendReview(empty,review),review.id,'hide','Spam','owner');expect(visibleReviews(hidden)).toHaveLength(0);expect(()=>appendReview(hidden,review)).toThrow('already_reviewed');const restored=moderateReview(hidden,review.id,'restore','Appeal accepted','owner');expect(visibleReviews(restored)).toHaveLength(1);expect(restored.reviews[0].history).toHaveLength(2)})
 it('rejects spoofed verification and invalid stars',()=>{expect(submitSchema.safeParse({productId:'gid://shopify/Product/1',orderId:'gid://shopify/Order/1',author:'A',rating:6,body:'Text',verifiedPurchase:true}).success).toBe(false)})
})
describe('server authorization',()=>{
 it('requires real authentication and exact owner ID',async()=>{vi.mocked(getValidAccessToken).mockResolvedValue(null);await expect(identity(true)).rejects.toMatchObject({status:401});vi.mocked(getValidAccessToken).mockResolvedValue('session');vi.mocked(queryCustomerAccountApi).mockResolvedValue({data:{customer:{id:'gid://shopify/Customer/2'}}});await expect(identity(true)).rejects.toMatchObject({status:403});vi.mocked(queryCustomerAccountApi).mockResolvedValue({data:{customer:{id:'gid://shopify/Customer/1'}}});expect((await identity(true)).isOwner).toBe(true)})
 it('fails closed without feature and owner configuration',async()=>{vi.stubEnv('REVIEW_OWNER_CUSTOMER_ID','');await expect(identity()).rejects.toMatchObject({status:503})})
 it('rejects cross-origin mutations and oversized input',async()=>{expect(()=>checkOrigin(new Request('https://www.atpgroupservices.ae/api/reviews',{headers:{origin:'https://evil.example','content-type':'application/json'}}))).toThrow('forbidden');const request=new Request('https://www.atpgroupservices.ae/api/reviews',{method:'POST',headers:{origin:'https://www.atpgroupservices.ae','content-type':'application/json'},body:'a'.repeat(9000)});await expect(readInput(request)).rejects.toMatchObject({status:413})})
 it('checks purchased product, follows order line pagination and rejects inaccessible orders',async()=>{vi.mocked(queryCustomerAccountApi).mockResolvedValueOnce({data:{order:null}});await expect(verifyPurchase('session','order','product')).rejects.toMatchObject({status:403});vi.mocked(queryCustomerAccountApi).mockResolvedValueOnce({data:{order:{lineItems:{nodes:[{productId:'other',quantity:1}],pageInfo:{hasNextPage:true,endCursor:'next'}}}}}).mockResolvedValueOnce({data:{order:{lineItems:{nodes:[{productId:'product',quantity:1}],pageInfo:{hasNextPage:false,endCursor:null}}}}});await expect(verifyPurchase('session','order','product')).resolves.toBeUndefined();expect(queryCustomerAccountApi).toHaveBeenLastCalledWith('session',expect.any(String),{id:'order',after:'next'})})
 it('never marks a different product as purchased',async()=>{vi.mocked(queryCustomerAccountApi).mockResolvedValue({data:{order:{lineItems:{nodes:[{productId:'other',quantity:1}],pageInfo:{hasNextPage:false,endCursor:null}}}}});await expect(verifyPurchase('session','order','product')).rejects.toMatchObject({status:403})})
})
describe('durable concurrent writes',()=>{
 it('re-reads on conflict instead of overwriting another buyer',async()=>{const other={...review,id:'b17c3869-a8de-4968-993f-a45f1a09be75',buyerId:'gid://shopify/Customer/2'};const responses=[{product:{status:'ACTIVE',metafield:null}},{metafieldsSet:{userErrors:[{code:'STALE_OBJECT'}]}},{product:{status:'ACTIVE',metafield:{jsonValue:{version:1,reviews:[other]},compareDigest:'new'}}},{metafieldsSet:{userErrors:[]}}];const fetch=vi.fn().mockImplementation(async()=>Response.json({data:responses.shift()}));vi.stubGlobal('fetch',fetch);await updateReviews('gid://shopify/Product/1',doc=>appendReview(doc,review));const body=JSON.parse(fetch.mock.calls[3][1].body);expect(body.variables.metafields[0].compareDigest).toBe('new');expect(JSON.parse(body.variables.metafields[0].value).reviews).toHaveLength(2)})
 it('fails closed on corrupt stored data',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({data:{product:{status:'ACTIVE',metafield:{jsonValue:{version:9},compareDigest:'x'}}}})));await expect(updateReviews('gid://shopify/Product/1',doc=>doc)).rejects.toMatchObject({status:502})})
})
