export const reviewCopy = {
 ar: {title:'تقييمات المشترين',write:'اكتب تقييمًا',name:'الاسم الظاهر',body:'تعليقك',rating:'التقييم من ٥',order:'اختر الطلب الذي اشتريت فيه المنتج',submit:'نشر التقييم',verified:'مشتري موثّق',empty:'كن أول من يقيّم هذا المنتج بعد شرائه.',login:'سجّل الدخول للتقييم',more:'تحميل المزيد',saved:'تم الحفظ',reason:'سبب الإخفاء أو الاستعادة',hide:'إخفاء',restore:'استعادة',hidden:'مخفي',published:'ظاهر',admin:'إدارة التقييمات',history:'سجل الإدارة',policy:'ننشر التجارب الإيجابية والسلبية. قد تُخفى الإساءة والمحتويات المزعجة أو المزيفة.',errors:{login_required:'سجّل الدخول أولًا.',forbidden:'ليس لديك صلاحية لهذا الإجراء.',purchase_required:'الطلب المحدد لا يحتوي على هذا المنتج أو لا يخص حسابك.',already_reviewed:'سبق أن قيّمت هذا المنتج.',invalid_input:'تحقق من الحقول المطلوبة.',unavailable:'التقييمات غير متاحة الآن. حاول لاحقًا.',capacity_reached:'تعذّر إضافة تقييم حاليًا. تواصل معنا.',retry:'تم تغيير البيانات. حاول مرة أخرى.'}},
 en: {title:'Buyer reviews',write:'Write a review',name:'Display name',body:'Your review',rating:'Rating out of 5',order:'Select the order containing this product',submit:'Publish review',verified:'Verified buyer',empty:'Be the first to review this product after buying it.',login:'Sign in to review',more:'Load more',saved:'Saved',reason:'Reason for hiding or restoring',hide:'Hide',restore:'Restore',hidden:'Hidden',published:'Visible',admin:'Manage reviews',history:'Moderation history',policy:'We welcome positive and negative experiences. Abuse, spam and fake content may be hidden.',errors:{login_required:'Please sign in first.',forbidden:'You do not have permission for this action.',purchase_required:'This order does not contain the product or does not belong to your account.',already_reviewed:'You have already reviewed this product.',invalid_input:'Check the required fields.',unavailable:'Reviews are unavailable right now. Please try again later.',capacity_reached:'Unable to add a review right now. Please contact us.',retry:'The data changed. Please try again.'}},
}
export async function reviewFetch(url: string, body?: unknown) {
 const response = await fetch(url, {cache:'no-store', ...(body ? {method:'POST', headers:{'Content-Type':'application/json'},body:JSON.stringify(body)} : {})})
 const data = await response.json()
 if (!response.ok) throw new Error(data.error || 'unavailable')
 return data
}
